parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                dbname: '%env(resolve:DATABASE_NAME)%'
                user: '%env(resolve:DATABASE_USER_NAME)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                driver: 'pdo_pgsql'
                charset: utf8,
                options:
                    20: true #PDO::ATTR_EMULATE_PREPARES
    orm:
        default_entity_manager:   default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection:       default

                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
#                    Redirect:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity/Redirect'
#                        prefix: 'App\Entity\Redirect'
#                        alias: Redirect
